apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld-01
  labels:
    app: helloworld-01
spec:
  containers:
  - name: k8s-demo
    image: amitvashist7/k8s-tiny-web
    ports:
    - name: nodejs-port
      containerPort: 80
