apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment-3
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-3
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: nodejs-port
          containerPort: 80
      nodeSelector:
        hardware: virtual
